[package]
name = "devp2p"
version = "0.2.2"
license = "Apache-2.0"
authors = ["Wei Tang <hi@that.world>"]
description = "Ethereum's devp2p protocol implementation in Rust."
repository = "https://github.com/sorpaas/devp2p-rs"

[dependencies]
dpt = { version = "0.2", path = "./dpt" }
rand = "0.3.12"
rlpx = { version = "0.2", path = "./rlpx" }
futures = "0.1"
tokio-io = "0.1"
tokio-core = "0.1"
secp256k1-plus = "0.5"
etcommon-bigint = "0.2"
etcommon-rlp = "0.2"
etcommon-block = "0.2"
etcommon-hexutil = "0.2"
log = "0.3"

[dev-dependencies]
env_logger = "0.3"
url = "1.5.1"
sha3 = "0.6"

[workspace]
members = [
  "./dpt",
  "./rlpx",
]