[package]
name = "devp2p"
version = "0.2.1"
license = "Apache-2.0"
authors = ["Wei Tang <hi@that.world>"]
description = "Ethereum's devp2p protocol implementation in Rust."
repository = "https://github.com/sorpaas/devp2p-rs"

[dependencies]
dpt = { path = "./dpt" }
rand = "0.3.12"
rlpx = { path = "./rlpx" }
futures = "0.1"
tokio-io = "0.1"
tokio-core = "0.1"
devp2p-secp256k1 = "0.5"
etcommon-bigint = "0.1"
etcommon-rlp = "0.1"
etcommon-crypto = "0.1"
etcommon-block = "0.1"
log = "0.3"

[dev-dependencies]
env_logger = "0.3"
url = "1.5.1"

[workspace]
members = [
  "./dpt",
  "./rlpx",
]